### PR TITLE
Allow widget to be used in offline profiles

### PR DESCRIPTION
**Pull request by Achiel**
No server interaction takes place so this widget is safe to be used in
offline navigation profiles.

### CODE REVIEW

**Comment by bartpoelmans** [comment]
Thanks for taking the effort of developing this widget further.

**Comment by Achiel** [comment]
But no merge? :(

**Comment by bartpoelmans** [comment]
Aaah, That still needs to be done of course. Will do this probably this afternoon then or next week…

**Comment by Achiel** [comment]
Hi, is there any chance that you'd be willing to merge and release this? There are actually quite a few people that would gladly use it in offline mode :)

Thanks!

**Comment by bartpoelmans** [comment]
Hi Achiel,

A new release is published in the mendix app store, waiting for approval.

Kr,
Bart

**Comment by Achiel** [comment]
Great, thanks a lot! Very much appreciated.

**Pull request merged**
